name = "LimitedLDLFactorizations"
uuid = "f5a24dde-3ab7-510b-b81b-6a72c6098d3b"
version = "0.4.0"

[deps]
AMD = "14f7f29c-3bd6-536c-9a0b-7339e30b5a3e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
julia = "^1.3.0"

[extras]
AMD = "14f7f29c-3bd6-536c-9a0b-7339e30b5a3e"
Metis = "2679e427-3c69-5b7f-982b-ece356f1e94b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["AMD", "Metis", "LinearAlgebra", "SparseArrays", "Test"]
